apiVersion: v1
kind: ConfigMap
metadata:
  name: serverhub-config
  namespace: serverhub
data:
  CORS_ORIGINS: "https://serverhub.georgeop.us,http://serverhub.georgeop.us,http://149.202.84.198"
  DATABASE_URL: "sqlite:///./data/serverhub.db"
