apiVersion: v1
kind: Pod
metadata:
  name: image-importer
  namespace: serverhub
spec:
  nodeName: ovhgrapmx01
  hostPID: true
  restartPolicy: Never
  containers:
    - name: importer
      image: alpine:3.20
      command: ["sleep", "3600"]
      securityContext:
        privileged: true
      volumeMounts:
        - name: import-dir
          mountPath: /host-import
  volumes:
    - name: import-dir
      hostPath:
        path: /tmp/serverhub-import
        type: DirectoryOrCreate
