apiVersion: v1
kind: Service
metadata:
  name: {{ include "serverhub.api.fullname" . }}
  labels:
    {{- include "serverhub.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "serverhub.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
