apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "serverhub.configName" . }}
  labels:
    {{- include "serverhub.labels" . | nindent 4 }}
data:
  CORS_ORIGINS: {{ .Values.config.corsOrigins | quote }}
  DATABASE_URL: {{ .Values.config.databaseUrl | quote }}
  ALLOW_REGISTRATION: {{ .Values.config.allowRegistration | quote }}
