apiVersion: v1
kind: Service
metadata:
  name: {{ include "serverhub.web.fullname" . }}
  labels:
    {{- include "serverhub.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "serverhub.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
